Repository rakudo/rakudo, pull requests merged in 2020-05, with the labels that each got.

#2226 Update CONTRIBUTING.md with regards to prefix `RT`
  CONTRIBUTING.md
Labels: meta

#3204 Issue #2092 | Clarify detached method error messaging.
  src/Perl6/Grammar.nqp
  t/05-messages/02-errors.t
Labels: LTA

#1188 Awesomify “malformed loop spec” errors
  src/Perl6/Grammar.nqp
Labels: has conflicts

#3628 Add :$chomp to Str.lines()
  src/core.c/Str.pm6
Labels: IO
